In [2]:
import pandas as pd  
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder ,OneHotEncoder
import pickle

In [3]:
data=pd.read_csv('Churn_Modelling.csv')

In [4]:
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [7]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [8]:
onehot_encoder_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [9]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [10]:
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [11]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [12]:
X = data.drop('EstimatedSalary',axis=1)
y= data['EstimatedSalary']

In [13]:
## split data into train and test

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

scaler= StandardScaler()

X_train=scaler.fit_transform(X_train)
X_test =scaler.transform(X_test)

In [14]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [15]:
## ANN with regression

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [16]:
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)
])
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

C:\Users\jaipr\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

log_dir = "regressionlogs/fit/"+ datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [19]:

## set up Early stopping

Early_Stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [20]:
## Train the model

history = model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorboard_callback,Early_Stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100315.3203 - mae: 100315.3203 - val_loss: 98365.5391 - val_mae: 98531.1562
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 100332.9922 - mae: 100332.9922 - val_loss: 96892.0625 - val_mae: 97057.9219
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 97817.8828 - mae: 97817.8828 - val_loss: 93096.8047 - val_mae: 93263.0469
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 93736.2812 - mae: 93736.2812 - val_loss: 86736.6328 - val_mae: 86898.1875
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 87142.3438 - mae: 87142.3438 - val_loss: 78495.2734 - val_mae: 78652.6172
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 78074.1719 - mae: 78074.1719 - val_loss: 69832.3672 - val_mae: 69997.1953
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 68986.2891 - mae: 68986.2891 - val_loss: 62214.1172 - val_mae: 62369.6641
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 61902.6133 - mae: 61902.6133 - val_loss: 56483.5156 - val_mae: 56635.9844
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 55721.0703 - mae: 55721.0703 - val_loss: 53180.2031 - val_mae: 53331.2617
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 52443.1406 - mae: 52443.1406 - val_loss: 51692.3477 - val_mae: 51834.2773
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51264.2617 - mae: 51264.2617 - val_loss: 51160.2422 - val_mae: 51287.2891
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51436.5820 - mae: 51436.5820 - val_loss: 51004.3633 - val_mae: 51121.1211
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50171.2305 - mae: 50171.2305 - val_loss: 50942.2852 - val_mae: 51053.0195
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50290.9648 - mae: 50290.9648 - val_loss: 50901.3516 - val_mae: 51008.9844
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50068.3398 - mae: 50068.3398 - val_loss: 50856.8828 - val_mae: 50963.3672
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50328.5352 - mae: 50328.5352 - val_loss: 50818.5156 - val_mae: 50923.4258
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50031.1719 - mae: 50031.1719 - val_loss: 50782.0938 - val_mae: 50886.5352
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50022.0469 - mae: 50022.0469 - val_loss: 50748.6562 - val_mae: 50852.8555
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49839.5508 - mae: 49839.5508 - val_loss: 50711.7812 - val_mae: 50815.2930
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49583.1602 - mae: 49583.1602 - val_loss: 50690.4297 - val_mae: 50792.4062
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49925.4023 - mae: 49925.4023 - val_loss: 50666.4844 - val_mae: 50768.5703
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49686.9922 - mae: 49686.9922 - val_loss: 50631.4375 - val_mae: 50733.5352
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49935.3633 - mae: 49935.3633 - val_loss: 50616.8281 - val_mae: 50717.6406
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50272.5898 - mae: 50272.5898 - val_loss: 50594.1680 - val_mae: 50693.5781
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49482.8008 - mae: 49482.8008 - val_loss: 50578.1406 - val_mae: 50675.9414
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49580.6406 - mae: 49580.6406 - val_loss: 50555.7148 - val_mae: 50652.5859
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49411.4961 - mae: 49411.4961 - val_loss: 50541.3359 - val_mae: 50637.1250
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49471.8008 - mae: 49471.8008 - val_loss: 50534.3398 - val_mae: 50627.7656
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50070.0977 - mae: 50070.0977 - val_loss: 50519.8594 - val_mae: 50611.7578
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49282.0234 - mae: 49282.0234 - val_loss: 50497.0508 - val_mae: 50588.4102
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49658.5156 - mae: 49658.5156 - val_loss: 50486.6758 - val_mae: 50576.7969
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49960.6953 - mae: 49960.6953 - val_loss: 50476.0156 - val_mae: 50565.6758
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49837.2930 - mae: 49837.2930 - val_loss: 50469.6758 - val_mae: 50556.9844
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49424.9844 - mae: 49424.9844 - val_loss: 50462.7109 - val_mae: 50549.0078
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49503.1992 - mae: 49503.1992 - val_loss: 50448.8320 - val_mae: 50534.4688
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49841.2617 - mae: 49841.2617 - val_loss: 50439.3242 - val_mae: 50524.0117
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 48929.9023 - mae: 48929.9023 - val_loss: 50429.3164 - val_mae: 50513.1836
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49699.3984 - mae: 49699.3984 - val_loss: 50437.9688 - val_mae: 50519.6367
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49955.0586 - mae: 49955.0586 - val_loss: 50419.0078 - val_mae: 50500.7930
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49542.5039 - mae: 49542.5039 - val_loss: 50421.7344 - val_mae: 50502.6602
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49105.1484 - mae: 49105.1484 - val_loss: 50401.3711 - val_mae: 50482.0586
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49161.5625 - mae: 49161.5625 - val_loss: 50406.8398 - val_mae: 50485.8047
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49212.4297 - mae: 49212.4297 - val_loss: 50414.0078 - val_mae: 50491.6250
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49545.6094 - mae: 49545.6094 - val_loss: 50408.4648 - val_mae: 50484.5742
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49422.3750 - mae: 49422.3750 - val_loss: 50393.2578 - val_mae: 50469.8125
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49975.1484 - mae: 49975.1484 - val_loss: 50384.7500 - val_mae: 50460.5391
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49721.1289 - mae: 49721.1289 - val_loss: 50392.8516 - val_mae: 50466.6523
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49266.6797 - mae: 49266.6797 - val_loss: 50396.4258 - val_mae: 50469.0508
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49306.7031 - mae: 49306.7031 - val_loss: 50381.5547 - val_mae: 50454.3086
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49478.6758 - mae: 49478.6758 - val_loss: 50380.0820 - val_mae: 50451.7852
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49148.9023 - mae: 49148.9023 - val_loss: 50383.0938 - val_mae: 50453.5273
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49197.4531 - mae: 49197.4531 - val_loss: 50383.4766 - val_mae: 50453.6016
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49587.8672 - mae: 49587.8672 - val_loss: 50377.3633 - val_mae: 50446.6914
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50078.6250 - mae: 50078.6250 - val_loss: 50377.9844 - val_mae: 50446.2266
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49243.5312 - mae: 49243.5312 - val_loss: 50384.3008 - val_mae: 50451.3047
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49361.7266 - mae: 49361.7266 - val_loss: 50376.9531 - val_mae: 50443.8711
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 48843.0039 - mae: 48843.0039 - val_loss: 50372.2930 - val_mae: 50438.9688
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49608.4219 - mae: 49608.4219 - val_loss: 50373.5234 - val_mae: 50439.9297
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49271.8242 - mae: 49271.8242 - val_loss: 50376.4727 - val_mae: 50442.1641
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49513.8398 - mae: 49513.8398 - val_loss: 50378.8359 - val_mae: 50443.2188
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49371.6836 - mae: 49371.6836 - val_loss: 50370.9961 - val_mae: 50435.8594
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49438.1406 - mae: 49438.1406 - val_loss: 50376.2422 - val_mae: 50439.7734
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49356.1562 - mae: 49356.1562 - val_loss: 50364.3125 - val_mae: 50428.0781
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49849.0586 - mae: 49849.0586 - val_loss: 50373.8359 - val_mae: 50436.8711
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49315.1758 - mae: 49315.1758 - val_loss: 50372.6953 - val_mae: 50434.8789
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49860.2695 - mae: 49860.2695 - val_loss: 50372.1406 - val_mae: 50434.0625
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49775.5508 - mae: 49775.5508 - val_loss: 50374.1133 - val_mae: 50435.7227
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49240.7656 - mae: 49240.7656 - val_loss: 50376.2109 - val_mae: 50437.7422
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49375.0352 - mae: 49375.0352 - val_loss: 50386.9961 - val_mae: 50447.7617
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50008.5117 - mae: 50008.5117 - val_loss: 50389.8711 - val_mae: 50449.1055
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49250.5000 - mae: 49250.5000 - val_loss: 50376.6484 - val_mae: 50436.3984
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49615.0352 - mae: 49615.0352 - val_loss: 50370.0781 - val_mae: 50430.1875
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49274.6250 - mae: 49274.6250 - val_loss: 50368.3945 - val_mae: 50427.7969

In [21]:
## Load Tensorboard Extension
%load_ext tensorboard

In [22]:
%tensorboard --logdir regressionlogs/fit

In [23]:
test_loss,test_mae = model.evaluate(X_test,y_test)
print(f"Test MAE : {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - loss: 51161.9531 - mae: 51163.9453
Test MAE : 50428.078125

In [24]:
model.save('regressionmodel.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.